### Get non sensitive diaries
GET http://localhost:3000/api/diaries

### Get a diary by id
GET http://localhost:3000/api/diaries/6

### Create diary
POST http://localhost:3000/api/diaries
Content-Type: application/json

{
  "date": "2017-01-06",
  "weather": "rainy",
  "visibility": "good",
  "comment": "this should work"
}